# Generated by Django 5.2.16 on 2026-07-22 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-grid-fill', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Theme Category',
                'verbose_name_plural': 'Theme Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, default='AI Portfolio Team', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD. 0 = free.', max_digits=8)),
                ('template_directory', models.CharField(blank=True, max_length=255)),
                ('configuration_file', models.CharField(default='manifest.json', max_length=255)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('supports_dark_mode', models.BooleanField(default=True)),
                ('supports_custom_colors', models.BooleanField(default=True)),
                ('supports_custom_fonts', models.BooleanField(default=True)),
                ('supports_animation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='themes/zips/')),
                ('extracted_path', models.CharField(blank=True, help_text='Path relative to MEDIA_ROOT where zip was extracted.', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated or uploaded preview image.', null=True, upload_to='themes/thumbnails/')),
                ('preview_image', models.ImageField(blank=True, help_text='High-resolution full preview screenshot image.', null=True, upload_to='themes/previews/')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags, e.g. 'dark, bootstrap, tailwind, portfolio'.", max_length=500)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_themes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='themes.themecategory')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('image', 'Image'), ('font', 'Font'), ('other', 'Other')], default='other', max_length=10)),
                ('file_path', models.CharField(help_text='Path relative to theme extracted_path.', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes.')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Theme Asset',
                'verbose_name_plural': 'Theme Assets',
                'ordering': ['asset_type', 'file_name'],
            },
        ),
    ]
