# Generated by Django 5.2.16 on 2026-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
