# Generated by Django 5.2.16 on 2026-07-20 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_thememapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.CharField(blank=True, default='AI Portfolio Team', max_length=150),
        ),
        migrations.AddField(
            model_name='theme',
            name='configuration_file',
            field=models.CharField(default='theme.json', max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='css_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='theme',
            name='default_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='font_family',
            field=models.CharField(default='Inter', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='High-resolution full preview screenshot image.', null=True, upload_to='themes/previews/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='supports_animation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='supports_custom_colors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='supports_custom_fonts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='supports_dark_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='template_directory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
