# Generated by Django 5.2.16 on 2026-07-13 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_portfolio_status_alter_portfolio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('returning_visitors', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Average session duration in seconds')),
                ('bounce_rate', models.FloatField(default=0.0, help_text='Bounce rate percentage')),
                ('seo_score', models.PositiveIntegerField(default=100)),
                ('performance_score', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Custom title tag override', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Search engine meta description snippet')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords list', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL referencing this index')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph sharing title', max_length=200)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description snippet')),
                ('og_image', models.ImageField(blank=True, help_text='OG Social Share Image', null=True, upload_to='seo/og_images/')),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter card title override', max_length=200)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter card description override')),
                ('favicon', models.ImageField(blank=True, help_text='Browser window favicon', null=True, upload_to='seo/favicons/')),
                ('robots_txt', models.TextField(default='User-agent: *\nAllow: /', help_text='Custom crawlers access rules')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(db_index=True, default='Desktop', max_length=50)),
                ('browser', models.CharField(db_index=True, default='Other', max_length=100)),
                ('referrer', models.CharField(db_index=True, default='direct', max_length=255)),
                ('country', models.CharField(db_index=True, default='Unknown', max_length=100)),
                ('path', models.CharField(db_index=True, default='Home', max_length=255)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
