# Generated by Django 5.2.16 on 2026-07-14 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_portfolio_status_alter_portfolio_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='The root or www domain, e.g. myportfolio.com', max_length=253)),
                ('subdomain', models.CharField(blank=True, help_text="Optional subdomain prefix, e.g. 'www' or 'portfolio'", max_length=63)),
                ('provider', models.CharField(choices=[('custom', 'Custom / Other'), ('namecheap', 'Namecheap'), ('godaddy', 'GoDaddy'), ('cloudflare', 'Cloudflare'), ('google', 'Google Domains'), ('aws_route53', 'AWS Route 53')], default='custom', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('active', 'Active'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verification_token', models.CharField(blank=True, help_text='Unique token placed in DNS TXT record for ownership proof.', max_length=64)),
                ('verification_method', models.CharField(choices=[('txt', 'TXT Record'), ('cname', 'CNAME Record')], default='txt', max_length=10)),
                ('dns_verified', models.BooleanField(default=False)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Primary domain used in public portfolio URL resolution.')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='portfolio.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=10)),
                ('detail', models.TextField(blank=True, help_text='DNS response or error detail.')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='domains.customdomain')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
