# Generated by Django 5.2.16 on 2026-07-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0003_thememapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, help_text='e.g. Senior Backend Engineer', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='A short tagline or catchphrase', max_length=255)),
                ('about', models.TextField(blank=True, help_text='Rich about me biography description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='portfolios/photos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='portfolios/covers/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, help_text='e.g. San Francisco, CA', max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='portfolios/resumes/')),
                ('social_github', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_portfolio', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('contact_form_action', models.URLField(blank=True, help_text='Custom POST link target for the contact form')),
                ('footer_copyright', models.CharField(blank=True, max_length=255)),
                ('footer_tagline', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='themes.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Portfolio',
                'verbose_name_plural': 'User Portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('year', models.CharField(help_text='e.g. 2018 or 2015 - 2019', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('duration', models.CharField(help_text='e.g. Jan 2020 - Present', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated stack, e.g. Python, Vue', max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolios/projects/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-gear-fill', help_text='Bootstrap Icons class name', max_length=100)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('language', 'Language'), ('framework', 'Framework / Library'), ('tool', 'Tool / DevOps')], default='technical', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, help_text='e.g. Intermediate, Expert', max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['skill_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150)),
                ('reviewer_role', models.CharField(blank=True, help_text='e.g. Product Lead, Google', max_length=150)),
                ('text', models.TextField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='portfolio.portfolio')),
            ],
        ),
    ]
