# Generated by Django 5.2.16 on 2026-07-20 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_organization'),
        ('themes', '0004_theme_author_theme_configuration_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('snapshot_json', models.JSONField(default=dict)),
                ('seo_snapshot', models.JSONField(blank=True, default=dict)),
                ('tag', models.CharField(default='Draft', help_text='e.g. Draft, Published, Rollback, Autosave', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_auto_save', models.BooleanField(default=False)),
                ('is_manual_save', models.BooleanField(default=False)),
                ('git_commit_sha', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portfolio_versions', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='portfolio.portfolio')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_versions', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Portfolio Version',
                'verbose_name_plural': 'Portfolio Versions',
                'ordering': ['-version_number', '-created_at'],
            },
        ),
    ]
