# Generated by Django 5.2.16 on 2026-07-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolioversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='build_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('BUILDING', 'Building'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='DRAFT', help_text='Current build state of the portfolio', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='build_time_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='css_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='html_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_publish_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_published_portfolios', to='portfolio.portfolioversion'),
        ),
        migrations.CreateModel(
            name='PortfolioBuildLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('step', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_logs', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Build Log',
                'verbose_name_plural': 'Portfolio Build Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
