# Generated by Django 5.2.16 on 2026-07-21 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_build_status_portfolio_build_time_ms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='GITHUB', max_length=50)),
                ('repository_name', models.CharField(max_length=255)),
                ('repository_url', models.URLField(blank=True, max_length=500)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('commit_sha', models.CharField(blank=True, max_length=100)),
                ('deployment_status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPLOYING', 'Deploying'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('deployment_url', models.URLField(blank=True, max_length=500)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_portfolio_deployments', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_deployments', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Deployment',
                'verbose_name_plural': 'Portfolio Deployments',
                'ordering': ['-created_at'],
            },
        ),
    ]
