# Generated by Django 5.2.16 on 2026-07-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfoliodeployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('tone', models.CharField(default='Professional', max_length=50)),
                ('length', models.CharField(default='Medium', max_length=50)),
                ('template_variant', models.CharField(default='Modern', max_length=50)),
                ('content_json', models.JSONField(default=dict, help_text='Stores greeting, introduction, body, closing, signature, evidence_map, coverage, metrics')),
                ('content_text', models.TextField(blank=True, help_text='Full compiled plain text cover letter')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('job_hash', models.CharField(blank=True, max_length=64)),
                ('resume_hash', models.CharField(blank=True, max_length=64)),
                ('portfolio_hash', models.CharField(blank=True, max_length=64)),
                ('metadata_json', models.JSONField(default=dict, help_text='Source, AI model, prompt version, generation time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Cover Letter Version',
                'verbose_name_plural': 'Cover Letter Versions',
                'ordering': ['-version_number', '-created_at'],
            },
        ),
    ]
