# Generated by Django 5.2.16 on 2026-07-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_coverletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resume_data_json', models.JSONField(default=dict)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_resumes', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Optimized Resume',
                'verbose_name_plural': 'Optimized Resumes',
                'ordering': ['-version_number', '-created_at'],
            },
        ),
    ]
