# Generated by Django 5.2.16 on 2026-07-22 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=200)),
                ('repository_owner', models.CharField(max_length=150)),
                ('branch_name', models.CharField(default='main', max_length=50)),
                ('deployment_version', models.PositiveIntegerField(default=1)),
                ('deployment_duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('deployment_message', models.CharField(blank=True, max_length=255)),
                ('pages_enabled', models.BooleanField(default=False)),
                ('last_commit_sha', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('published_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='themes.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Deployment Log',
                'verbose_name_plural': 'GitHub Deployment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(help_text='e.g. my-glass-portfolio', max_length=200)),
                ('repository_owner', models.CharField(help_text='GitHub username of the owner', max_length=150)),
                ('branch_name', models.CharField(default='main', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_configs', to='themes.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Repository Config',
                'verbose_name_plural': 'GitHub Repository Configs',
            },
        ),
    ]
