import urllib.request
import urllib.error
import json


def github_api_request(url, token, data=None, method="GET"):
    """
    Standard HTTP utility wrapper to call GitHub API securely.
    """
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "AI-Portfolio-Builder-SaaS"
    }
    req_data = None
    if data is not None:
        req_data = json.dumps(data).encode("utf-8")
        headers["Content-Type"] = "application/json"

    req = urllib.request.Request(url, data=req_data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as res:
            res_body = res.read().decode("utf-8")
            if res.status == 204 or not res_body:
                return {}, res.status
            return json.loads(res_body), res.status
    except urllib.error.HTTPError as e:
        err_content = e.read().decode("utf-8")
        try:
            err_json = json.loads(err_content)
            err_msg = err_json.get("message", "GitHub API error.")
        except Exception:
            err_msg = err_content or str(e)
        raise Exception(f"{err_msg} (HTTP {e.code})")
    except Exception as e:
        raise Exception(f"Failed to communicate with GitHub API: {str(e)}")


def get_authenticated_username(token) -> str:
    """
    Queries GitHub user endpoint to retrieve owner login name.
    """
    data, _ = github_api_request("https://api.github.com/user", token)
    return data.get("login", "")


def list_repositories(token):
    """
    Lists repositories owned directly by the connected user.
    """
    repos, _ = github_api_request("https://api.github.com/user/repos?type=owner&per_page=100", token)
    # Sort alphabetically by name
    return sorted(repos, key=lambda x: x["name"].lower())


def create_repository(token, name) -> dict:
    """
    Creates a new public repository under the user's personal profile.
    Automatically initializes the repo with a README to ensure a main branch exists.
    """
    payload = {
        "name": name,
        "description": "My professional resume portfolio website generated by AI Portfolio Builder",
        "private": False,
        "auto_init": True
    }
    repo, _ = github_api_request("https://api.github.com/user/repos", token, data=payload, method="POST")
    return repo
